/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as WorkspaceSequencingMarginLabRouteImport } from './routes/_workspace.sequencing-margin-lab'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSequencingMarginLabRoute =
  WorkspaceSequencingMarginLabRouteImport.update({
    id: '/sequencing-margin-lab',
    path: '/sequencing-margin-lab',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/sequencing-margin-lab': typeof WorkspaceSequencingMarginLabRoute
}
export interface FileRoutesByTo {
  '/sequencing-margin-lab': typeof WorkspaceSequencingMarginLabRoute
  '/': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/sequencing-margin-lab': typeof WorkspaceSequencingMarginLabRoute
  '/_workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sequencing-margin-lab'
  fileRoutesByTo: FileRoutesByTo
  to: '/sequencing-margin-lab' | '/'
  id:
    | '__root__'
    | '/_workspace'
    | '/_workspace/sequencing-margin-lab'
    | '/_workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/sequencing-margin-lab': {
      id: '/_workspace/sequencing-margin-lab'
      path: '/sequencing-margin-lab'
      fullPath: '/sequencing-margin-lab'
      preLoaderRoute: typeof WorkspaceSequencingMarginLabRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceSequencingMarginLabRoute: typeof WorkspaceSequencingMarginLabRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceSequencingMarginLabRoute: WorkspaceSequencingMarginLabRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
